### ISSUE TITLE
Request to update data 

### ISSUE THREAD

**Issue by mtsaiko** [Jester565/DisneylandData#1]
Is it possible to refresh the data collection or at least publish the code that scraped this ?   This is hugely interesting data.  Not sure if you have the original code handy but would love to get this going for recent period.       Didn’t see any contact info on your website. Linkedin 3rd degree from you.

**Comment by Jester565** [comment]
[Here](https://drive.google.com/drive/folders/1b8lQy2YQo2cSgTN5jk_a789IyoEt5VIX?usp=sharing) is the most recent data I have. I think there are some gaps in the data for various reasons and I stopped data collection in early 2020.

While I do have code that saves the wait times [here](https://github.com/Jester565/ParkHeroJS/blob/master/dis/Ride.js#L70), I would recommend using the [themeparks library](https://github.com/cubehouse/themeparks) since its well maintained. An example of what the function would look like using their library is shown below.

If you're interested in scraping park schedules, ride information, weather, and some other stuff then [ParkHeroJS](https://github.com/Jester565/ParkHeroJS) is a decent starting point though I imagine a lot with their website has changed since the pandemic.

Feel free to message me at Jester565#6443 on Discord if you have any questions.

```
async function getRideTimesForPark(token, parkID) {
    let park = null;
    if (parkID == '330339') {
        if (DisneyInstance == null) {
            DisneyInstance = new ThemeParks.Parks.DisneylandResortMagicKingdom();
        }
        park = DisneyInstance;
    } else if (parkID == '336894') {
        if (CaInstance == null) {
            CaInstance = new ThemeParks.Parks.DisneylandResortCaliforniaAdventure();
        }
        park = CaInstance;
    }
    let rides = await park.GetWaitTimes();
    let rideTimes = [];

    for (let ride of rides) {
        let rideTime = {
            status: null,
            fastPassTime: null,
            waitMins: null
        };
        let underscoreIdx = ride.id.lastIndexOf('_');
        if (underscoreIdx >= 0) {
            rideTime["id"] = parseInt(ride.id.substr(underscoreIdx + 1));
            rideTime["name"] = ride.name;
            if (ride.waitTime != null && ride.waitTime != 0) {
                rideTime.waitMins = ride.waitTime;
                if (ride.meta && ride.meta.fastPassStartTime) {
                    rideTime["fastPassTime"] = ride.meta.fastPassStartTime;
                }
            }
            rideTime["status"] = ride["status"];
            rideTimes.push(rideTime);
        }
    }
    return rideTimes;
}
```
